## 1) nn.Conv2d 
 : 2-dim 데이터에 하나의 Convolution layer를 생성
##### 필요한 하이퍼파라미터를 설정하면 Convolution layer에 필요한 parameter weight를 자동으로 선언해준다.

- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html)

![image.png](http://drive.google.com/uc?id=1YX0AvzjTVFD38dhVZ2-bbv5gLEk9A8K8)
![image.png](http://drive.google.com/uc?id=18ZaNZcwh4SOBSa8WmXtGgQM4iDi6q6F5)

In [ ]:
import torch
import torch.nn as nn

### Example 1) kernel_size=3, stride=1, padding=0
![image.png](http://drive.google.com/uc?id=1dvnKVDptCOD1VLtiiTztOB2Lp4SAkuOE)

In [ ]:
input = torch.ones(1,1,4,4)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0)
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 2, 2])


### Example 2) kernel_size=3, stride=2, padding=0
![image.png](http://drive.google.com/uc?id=1SgTHZ4mGkQgaHmpVNi-IcHqP1pW5Crm0)

In [ ]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0)
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 2, 2])


### Example 3) kernel_size=4, stride=1, padding=2
![image.png](http://drive.google.com/uc?id=1jA5h5lM6mbMtRtBT8rRFacf6yQazmHzW)


In [ ]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=4, stride=1, padding=2)
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 6, 6])


### Excercise 1) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=1uAgXHskAXGtdowxGKw99Dtw4n4f_X34s)


In [ ]:
input = torch.ones(1,1,6,6)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 3, 3])


### Excercise 2) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=1Q2WLIYER2T5h8Pri9diRs3J_Kmjb7MXo)


In [ ]:
input = torch.ones(1,1,5,5)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=1)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 5, 5])


### Excercise 3) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=15MRDXon_68pySZHQy9wBqdbwp8HQNdv8)


In [ ]:
input = torch.ones(1,1,5,5)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 3, 3])


### Excercise 4) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=17yCuQSaW2Q0XUwwHG8tBvts15Y-U3we1)

In [ ]:
input = torch.ones(1,1,5,5)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=2)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

### Excercise 5) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=1fNZTyHOtHX0y7sFW-e6tx0qP8mrQ7wK8)

In [ ]:
input = torch.ones(1,3,5,5)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=3, out_channels=2, kernel_size=3, stride=2, padding=1)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 2, 3, 3])


### Excercise 6) Input size=(7,7), kernel_size=3, stride=2, padding=0, Output size=?
![image.png](http://drive.google.com/uc?id=1d9C1FkXHRwx86OfBZ2-1XrIVyak_skMG)

In [ ]:
input = torch.ones(1,1,6,6)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=?, stride=?, padding=?)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 2, 2])


## < Convolution output feature map size 계산 > 
![image.png](http://drive.google.com/uc?id=12reHf9xtapZrVBG4LlNbNGa37ZeFfUqk)
![image.png](http://drive.google.com/uc?id=1iqd-9-hHgnc6Zz7kR6v9EMhLWrMmY07N)

In [ ]:
# 예제 1)
########################################## Complete This Code~!
ans_1 = int( (227 - 11 + 2*0) / 4 + 1 )
########################################## Complete This Code~!
print(f'예제 1 정답 : {ans_1}')

# 예제 2)
ans_2 = int( (64 - 7 + 2*0) / 2 + 1 )
print(f'예제 2 정답 : {ans_2}') # 28.5 + 1 => 29

# 예제 3)
########################################## Complete This Code~!
ans_3 = int( (32 - 5 + 2*2) / 1 + 1 )
########################################## Complete This Code~!
print(f'예제 3 정답 : {ans_3}')

# 예제 4)
# <Height>
ans_4_height = int( (32 - 5 + 2*0) / 1 + 1 )
# <Width>
ans_4_width = int( (64 - 5 + 2*0) / 1 + 1 )
print(f'예제 4 정답 : ({ans_4_height}, {ans_4_width})') # (28, 60)

# 예제 5)
# <Height>
########################################## Complete This Code~!
ans_5_height = int( (64 - 3 + 2*1) / 1 + 1 )
########################################## Complete This Code~!
#<Width>
########################################## Complete This Code~!
ans_5_width = int( (32 - 3 + 2*1) / 1 + 1 )
########################################## Complete This Code~!
print(f'예제 5 정답 : ({ans_5_height}, {ans_5_width})')

예제 1 정답 : 55
예제 2 정답 : 29
예제 3 정답 : 32
예제 4 정답 : (28, 60)
예제 5 정답 : (64, 32)


In [ ]:
# 각 예제에 맞게 INPUT 값을 바꾸어 설정할 수 있습니다.
INPUT_SIZE = (227,227)
IN_CHANNELS = 3
OUT_CHANNELS = 10
KERNEL_SIZE = 11
STRIDE = 4
PADDING = 0

input = torch.ones(1,IN_CHANNELS,INPUT_SIZE[0],INPUT_SIZE[1])
func = nn.Conv2d(in_channels=IN_CHANNELS, out_channels=OUT_CHANNELS, kernel_size=KERNEL_SIZE, stride=STRIDE, padding=PADDING)
output = func(input)
print(output.shape)

torch.Size([1, 10, 55, 55])


## 2) nn.MaxPool2d 
- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html)

![image.png](http://drive.google.com/uc?id=1010fN_7lMHuxmda3_gdSxfbW36yTC6F5)
![image.png](http://drive.google.com/uc?id=1D2e9iFzJZMPLxRYucC4LS2B44-a3dlQk)

![image.png](http://drive.google.com/uc?id=1xEmoXL-lmanXO6eSYDEmq7_cyFB73dRF)

In [ ]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]])
print(input)
func = nn.MaxPool2d(kernel_size=2)
output = func(input)
print(output)

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])
tensor([[[6., 8.],
         [3., 4.]]])


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


## 3) nn.AvgPool2d
- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.AvgPool2d.html)

![image.png](http://drive.google.com/uc?id=1z4OjHBduieJQVJqquISgrsmVqlVlfgS1)
![image.png](http://drive.google.com/uc?id=10U4Z4OGKSWQHeDMa-f9KRnUXhfGKhKnk)

![image.png](http://drive.google.com/uc?id=1wg2vJ8t780P6l5EUw1oLF3QTSjZBse0a)


In [ ]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]])
print(input)
func = nn.AvgPool2d(kernel_size=2)
output = func(input)
print(output)

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])
tensor([[[2.7500, 4.7500],
         [1.7500, 1.7500]]])


## 4) nn.AdaptiveAvgPool2d()
- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.AdaptiveAvgPool2d.html)

![image.png](http://drive.google.com/uc?id=190yR-M7yTb6ZlILOi4J5RSrfLeh_iul8)

![image.png](http://drive.google.com/uc?id=1KMgjceD4tsS67kUvAb1BYC29HXWJb0Hr)


In [ ]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]]) # shpae : [1,4,4]
print(input)
func = nn.AdaptiveAvgPool2d(1)
output = func(input)
print(output) # shape : [1,1,1]

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])
tensor([[[2.7500]]])


In [ ]:
input = torch.randn((1,3,4,4))
print(input)
func = nn.AdaptiveAvgPool2d(1)
output = func(input)
print(output) # shape : [1,3,1,1]

tensor([[[[-0.3266, -1.5027,  0.0539,  1.0338],
          [ 0.8418,  0.5582, -0.2954, -1.2928],
          [-0.0594,  1.6513,  0.5284, -0.2285],
          [-0.1334, -0.9264,  0.1005, -0.8065]],

         [[ 1.4910, -1.2344,  1.4647,  1.0041],
          [-0.8399, -0.3653,  1.8331, -1.1411],
          [ 1.1190, -0.0493, -0.3574, -0.7682],
          [ 0.3524, -0.6973, -0.6097,  0.8578]],

         [[-1.1336, -0.2463, -0.5406,  0.5991],
          [-0.0964,  0.0609, -1.5864,  0.3134],
          [ 1.4653,  1.2463,  0.7695,  1.6617],
          [-0.4497,  2.1768,  1.0994, -0.7260]]]])
tensor([[[[-0.0502]],

         [[ 0.1287]],

         [[ 0.2883]]]])


In [ ]:
input = torch.randn((1,3,1,1))
print(input)
func = nn.AdaptiveAvgPool2d(7)
output = func(input)
print(output) # shape : [1,3,7,7]

tensor([[[[-1.0636]],

         [[ 0.7998]],

         [[-1.7271]]]])
tensor([[[[-1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636],
          [-1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636],
          [-1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636],
          [-1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636],
          [-1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636],
          [-1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636],
          [-1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636, -1.0636]],

         [[ 0.7998,  0.7998,  0.7998,  0.7998,  0.7998,  0.7998,  0.7998],
          [ 0.7998,  0.7998,  0.7998,  0.7998,  0.7998,  0.7998,  0.7998],
          [ 0.7998,  0.7998,  0.7998,  0.7998,  0.7998,  0.7998,  0.7998],
          [ 0.7998,  0.7998,  0.7998,  0.7998,  0.7998,  0.7998,  0.7998],
          [ 0.7998,  0.7998,  0.7998,  0.7998,  0.7998,  0.7998,  0.7998],
          [ 0.7998,  0.7998,